name: main_app
description: A Flutter app shell.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  provider: ^6.1.5+1
  flutter_riverpod: ^2.5.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.8.0+1
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  two_dimensional_scrollables: ^0.3.0
  usb_serial: ^0.5.0
  device_info_plus: ^10.1.2

flutter:
  uses-material-design: true
